---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.2p198
      Hawkular-Tenant:
      - rdis
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '154'
      Date:
      - Tue, 28 Nov 2017 17:28:12 GMT
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=73762a0d783a513e7d44e44623f876c5; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAA3MvQ7CIBiF4XthFsJfK3Fr1aqDizTulH5NSIA2QF2M9y7TWZ7zftETSnI2a0gfZwGdkB6713i9oAN6hM1DgFhMcWvEb0i5biWU8JYwMrhofHX97nzBQ1oDvrmC9b1jFclmYlJZJSTMLadMLawRlgumjpOUojUgOVUL1MDZ5GzinEy97Rv6/QHfcrqrlgAAAA==
    http_version: 
  recorded_at: Tue, 28 Nov 2017 17:28:12 GMT
- request:
    method: post
    uri: https://capture.context.com/hawkular/metrics/m/stats/query
    body:
      encoding: UTF-8
      string: '{"start":1511886402000,"end":1511887062000,"bucketDuration":"60s","tags":"descriptor_name:network/tx_rate|network/rx_rate|cpu/usage_rate|memory/usage,type:pod,host_id:capture.context.com,pod_id:4bb31a97-bca3-11e7-94bc-001a4a2314d6"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.2p198
      Hawkular-Tenant:
      - rdis
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
      Content-Length:
      - '252'
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '1101'
      Date:
      - Tue, 28 Nov 2017 17:28:12 GMT
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=73762a0d783a513e7d44e44623f876c5; path=/;
        HttpOnly; Secure
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAANVYXW/rNgz9L3luVfFLJPu+XzEMg9tmxcVu2iJNt3tR9L+PjpvYSZw5KRzM85tlKTqkdM4h8z57rN4e57Pb99nL88MN390RVK7Xd/cVXQPM9dr57v46Z6i4QgJ+KDeL+eJ5+fPm7bWqF/76PntdVcvV7BYEwKxwxpzz1Wz+9NCOlWZs8e1pduvkCGgp3qu/HnfeF/OHb9XulEX1Y+f99W0RP5tMjVHKLxoj1eLl+/x1doux6eJl9XN2+0f1/XX+cXUArRxCE5wEtA2MHWg2DWh2CK3wJKBtYHShaZ4ENO2hgU6DBtpDA5sGDayHBjYNGlgPDXwaNPBDGmieBA22MHag/Sc0+O3qdIt7mq/+fl7+ebP68fuyWn3J5YC3IYEkJEFninNiyFDa2Jpp67CgJNYs9VXjHJeNPsOjfDg+nuUBJUDZIKVEDlrUNcTVEKiD9HNig5VS+IKQuChRyHD5BIslqdHeh/FccBctpwCq/XndQXsks+gpcH4xs4O2CJjWpx7fKBcQpDbLDGqSOaAba+ni7lnUxMCJDVWcVTRbztZmPBIeRPOgVnE5K4hBA4WcSDMVdwDwQGttEE4CxpFA8eLInSB6FjVBaJINbA3W7s0Z0V136ZePES63HMujWuj/4fAHzbYmGAU3EERYijC1KQUu4KZx/IxIu4p2sKgJQpKsH2IqqN7RN3Qkj9/ybMx6XhBDtrwvGRTSrQYcDAbAowL3CbagK2VE3gqcpWJ578N4Tn0gx1SKkxZSQofjaixsZCqoXAtTeztKqPDO+HjOfVwaMIXuS3iPE0t2tFOk4egV5xRGAxiTi2cwkZFM/v7lrWliv+zxuNUY7EoMbhUGtwLD5+nLsG238lZL6ja9PVvTeVsPevDloh621ItFPWiEl4t62MsuFvWwjV1s60HzuVzCBy3jclsP6v/Ftj5Bz8c66690Wsuvd1pRSYLHY1ZXorl2uSaBdXVfP4zRJAh33LNnyTpCakMUP5gyonyjpI3Jh0mHq4W5c23VwUns4FxPa5JfklCtkM5FVYl5AzQwH3wYUe07SC2p9ILr5q0p8cfT/PD/XD/gOYKzQtRJXDGPPrVETenShdazpsmiJaAoPSPhUVFl1jaJ6/EYhKx1oTWmdeSolqPiVDHKOWrP7Q3VlJUDYuwomTx3yui+RU2uuc01780Z1Xb+hVfAGIOFo/QvEcEJxAoVMVFAJrQChJvqTixh/QHQjCV6hlHta/J3Z9gFo90gEC1CFhmMIrg9hSiyzc3rViTWdIrsvkXNMUSrVT+Bl2MzxfYUosZWD/QoHuvOamqG/bSjIdH2lyj9IXTdKYOWfkH5BBoXBaxk2vxrIJJ0f3xE8+3glBQdCkbDUaKxjlPSY6pMiGI5Tl+QGbaqDMkOPozn1cclpZYECi2JJiu6LOATFOXYxeaam8Fv5xxt5PqGHff8j49/ACoIxQNMHAAA
    http_version: 
  recorded_at: Tue, 28 Nov 2017 17:28:12 GMT
recorded_with: VCR 3.0.3
