---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Cache-Control:
      - no-cache
      X-Powered-By:
      - Undertow/1
      Server:
      - JBoss-EAP/7
      Date:
      - Tue, 20 Nov 2018 09:11:11 GMT
      Vary:
      - Origin,Accept-Encoding
      Content-Type:
      - application/json
      Content-Length:
      - '158'
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=89055ff757c4f9ad281ca1bbe860a436; path=/;
        HttpOnly; Secure
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAA2MsQ7CIBQA/4VZCBC0rVurVh1cbOP+gNdIUmgD1MX47zLdcndf8sAcnUkDxo8zSI5kGNvneDmTHbn7dUaPIUN2S6AvjKmwKJzJminWuwAzjWjfkKkoQbe5OdM+Lp5eXabDrRXFbqYJamsPqtbAtVTamr00ohIVNJobDigmoSpZBidICYKNULJtJb8/6aNhB58AAAA=
    http_version: 
  recorded_at: Tue, 20 Nov 2018 09:11:11 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/m?tags=type:none
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 204
      message: No Content
    headers:
      Cache-Control:
      - no-cache
      Vary:
      - Origin,Accept-Encoding
      X-Powered-By:
      - Undertow/1
      Server:
      - JBoss-EAP/7
      Date:
      - Tue, 20 Nov 2018 09:11:11 GMT
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=89055ff757c4f9ad281ca1bbe860a436; path=/;
        HttpOnly; Secure
    body:
      encoding: UTF-8
      string: ''
    http_version: 
  recorded_at: Tue, 20 Nov 2018 09:11:11 GMT
recorded_with: VCR 3.0.3
