---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Cache-Control:
      - no-cache
      X-Powered-By:
      - Undertow/1
      Server:
      - JBoss-EAP/7
      Date:
      - Tue, 20 Nov 2018 09:11:04 GMT
      Vary:
      - Origin,Accept-Encoding
      Content-Type:
      - application/json
      Content-Length:
      - '158'
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=89055ff757c4f9ad281ca1bbe860a436; path=/;
        HttpOnly; Secure
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAA2MsQ7CIBQA/4VZCBC0rVurVh1cbOP+gNdIUmgD1MX47zLdcndf8sAcnUkDxo8zSI5kGNvneDmTHbn7dUaPIUN2S6AvjKmwKJzJminWuwAzjWjfkKkoQbe5OdM+Lp5eXabDrRXFbqYJamsPqtbAtVTamr00ohIVNJobDigmoSpZBidICYKNULJtJb8/6aNhB58AAAA=
    http_version: 
  recorded_at: Tue, 20 Nov 2018 09:11:04 GMT
- request:
    method: post
    uri: https://capture.context.com/hawkular/metrics/m/stats/query
    body:
      encoding: UTF-8
      string: '{"start":1542644802000,"end":1542645462000,"bucketDuration":"60s","tags":"descriptor_name:network/tx_rate|network/rx_rate|cpu/usage_rate|memory/working_set,type:node,host_id:yaacov-3-master001.10.35.48.34.nip.io"}'
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.2 (linux-gnu x86_64) ruby/2.4.1p111
      Hawkular-Tenant:
      - _system
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
      Content-Length:
      - '213'
  response:
    status:
      code: 200
      message: OK
    headers:
      Content-Encoding:
      - gzip
      Cache-Control:
      - no-cache
      X-Powered-By:
      - Undertow/1
      Server:
      - JBoss-EAP/7
      Date:
      - Tue, 20 Nov 2018 09:11:05 GMT
      Vary:
      - Origin,Accept-Encoding
      Content-Type:
      - application/json
      Content-Length:
      - '1712'
      Set-Cookie:
      - a054b5d9e987bf679f10c9d29be39478=89055ff757c4f9ad281ca1bbe860a436; path=/;
        HttpOnly; Secure
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAAK2Z3W7cNhOG72WPU5rzw+HQ572KD0WxSLeu0a4T2E7bIMi99+VKK5HStrLy5czgkuYz/8PRl8PD8dPD6XD/5XA+vv/t8el09/l4fP/hzx/kh/Px5fX0HCMFikFSUA+i4enxY3j8cPd0ev3rw/Pvd89///x8fMU/+N+Xw8vr8fn1cE9J2VQ9cozx3eH09Mu8ZsPa+fEJa0ViUGZWYopFcnp3OP75cLjnbCUkc8rGVpIQ48Tpl8fjvxw6H/8+3ItFD5mUiISdGOsvn86H+5SkBBKTxPgr2uWH4/njH6cX3AS888fXz4f7X49/vJy+vlsJYWshCjdCMGXox0jyQDrJQIVCcUBJcR0wRxFuHLlIwEwcnGIuFCnZJIGKSyiZyXIxz7v4r6wdv3dGiBZyioSNObYCQMMhiVq0IpKKeGuE9aFBhJQtCH4uNLFeRFCIgH/EJG6Z9grhKyFS1M4IAlbolT2NmrvIAG4PGsXcEsvSCqszFxE0eQpYw72jcS4SgNqCxyxZou60wgTbCkCxFSAjxOJITTkqfFxZfHTkiXncNjg8HCgGd83WOIto9H71zZS0DthEfcCqBmiz+KyEwVdiRMCSG6XMXC9ufWV9aPCVmFPAP2dV0ti4e6SCA5mFZhO8XYh1wCbuApajhpTdU1amRgasBYfqXdYRuz4ziID4RSRPiWhIOFBCyBqL7Y/XCbXD7+I1Fw+srEI2am1wmhIlmLhyzgtPv3FkNECsim4dbXAhuHlADvaUdns63whV6UI1grPJMoLyEhHgZnZNepPWp61jbinAzZREODaRiQzFgYq162/mlRuRqV1kUkkBOc6mqjJyawluxdjHmjLnleWBkT7WMFimFTUIlaVU79uJrjfCVbtwRfVBMk6WJ/uO0UqolLnExCtXWR8Z6CnnhQuNsSo5pISitekqP73b2WGcT+cPz5/vapfx+PTw88vp9VuaDKQYiOrCwj+WUQF1zWMqMXpduwq/2HoR/LKVRLNrXbsIDYeFhog8kv1I8bu2E/W+uhpNO9xcuJSBocVttl5xnVKBaAtcFLWCZLQTd7N7qAwISfaFdrkC2wq32TppV10T4qjD1VSBeTfuVp8wMEBreeEMXGrqWuNOWyftwtdvOENCFkg7nWG7K6j3KUE/2VpcRwJJceSacdutE25NN+ikO9wcDVlXdSfuZntwYUAyluG+CVcNCGQr3HnrhKs5uluvXbSfRDUmd+JuNQL1vlrqsmqPy5dee4nbbG1w3cx77aJsouPZjbtZ+Ot9SFi+dAYqXmjlC83OiVbc0ZMslCsF3r/XFTarfI2eAm0l6gMNOUhMV4HWbJ1oUaR4FWilIB7L3kDbLPIXBpRDdu9x8VJbB1q7dUpjBY0AHg09ruPm/YG2Wdgv96GTWODCKI6Etcq6zdbZc43igtaUajLeSLq7y/j7j5/uPr0cH07fPifgMr+NxC4PoGu/Mvx0EYtU6t8XeeAl4fsWZiKZIQhNTwMx/DRAMM8QUMX3LbdErSakh2g14TOE5Z0QW0UU3VBnjhZi+GmAkNKYQ3ZBbJfGaoIJAg/MThN5hsiNObzsg9h+D7cQg+FvQnCeIVR3QmyVMZTGxhyx0wQ3jimtT9A+iO1XaTu+oIU55pHF6KQDBO80x2bR6TWh/6oJtUYTOyE2SwlxowleQDSa4EYTuhNi++XHjWOK9Bkz3w5Rs/+E2J33rwPi1/9jQIxXtAUsUDdaRTeYCQ9Yd7TCpX+/rk6M2q7vV5mnN6MHJpSMhDaJdo8k31Av0BsGLs2UDO4ADWXE9PW+Jls0m0fbEEGvw+h1RlYvOWiJ12nmdywunmFCSTFdlTpA1wFdiOh002I8s9o/hjj03gk5gMdYi1JJee+I5g0FKcKQ7chzBEcnH0REi8WllywOjOTo/AO64WGCOZGjo9dgZug9d3rJG8oYmrYUFtNUMssW1vOw5ebxo0FCROP9OY4shwkevEbCN4zDNkse3mISmlndqGo2DknW8bjcPiqa4draf+Rg9NS1Wd0fi28okQgjbue0YzgWzQFhsfLs1f5rtjQI431AQvMp1Hf3bl1vFlU8M1KwOE8MJ2WXkBRvTFlqe3ng6tcuyM3cJ79Yv4vhlbj/e8wbKjEYcmiQCyG99d8y5j0jJTnSCTVx5zDC3m8Ym/XZM1zVuHg3EkVFQRQZ3fhOtDow4CIfYDkuKkpSWIC/6RvRdlGPtdLm66B41Gxt+RS1YsW92D5QI/EVFOtaDTpfYIsBJW0b+6evX/8BYln1ZzMeAAA=
    http_version: 
  recorded_at: Tue, 20 Nov 2018 09:11:05 GMT
recorded_with: VCR 3.0.3
