---
http_interactions:
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Thu, 22 Dec 2016 07:42:31 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:31 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/counters/registry%2F8a36ac1d-bb99-11e6-8a18-001a4a2314d5%2Fcpu%2Fusage/stats/?bucketDuration=20s&start=1482306053000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Thu, 22 Dec 2016 07:42:33 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1482306053000,"end":1482306073000,"min":3.076499063124E12,"avg":3.076522023415E12,"median":3.076499063124E12,"max":3.076544983706E12,"sum":6.15304404683E12,"samples":2,"empty":false},{"start":1482392533000,"end":1482392553000,"min":3.286007338232E12,"avg":3.286007338232E12,"median":3.286007338232E12,"max":3.286007338232E12,"sum":3.286007338232E12,"samples":1,"empty":false}]'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:33 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/status
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Content-Type:
      - application/json
      Content-Length:
      - '133'
      Date:
      - Thu, 22 Dec 2016 07:42:33 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '{"MetricsService":"STARTED","Implementation-Version":"0.21.5.Final","Built-From-Git-SHA1":"e779588593f13224225356a94f1d8642fbccb30f"}'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:33 GMT
- request:
    method: get
    uri: https://capture.context.com/hawkular/metrics/gauges/registry%2F8a36ac1d-bb99-11e6-8a18-001a4a2314d5%2Fmemory%2Fusage/stats/?bucketDuration=20s&start=1482306073000
    body:
      encoding: US-ASCII
      string: ''
    headers:
      Accept:
      - application/json
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - rest-client/2.0.0 (linux-gnu x86_64) ruby/2.3.1p112
      Hawkular-Tenant:
      - default
      Authorization:
      - Bearer theToken
      Content-Type:
      - application/json
  response:
    status:
      code: 200
      message: OK
    headers:
      X-Powered-By:
      - Undertow/1
      Server:
      - WildFly/10
      Transfer-Encoding:
      - chunked
      Content-Type:
      - application/json
      Date:
      - Thu, 22 Dec 2016 07:42:34 GMT
      Set-Cookie:
      - f5489604a2df0d7b0e8c7b7b0a17e360=eba450abe5a9ff4df0d24483d1024dfa; path=/;
        HttpOnly; Secure
      Cache-Control:
      - private
    body:
      encoding: UTF-8
      string: '[{"start":1482306073000,"end":1482306093000,"min":1.645568E8,"avg":1.645568E8,"median":1.645568E8,"max":1.645568E8,"sum":3.291136E8,"samples":2,"empty":false},{"start":1482392553000,"end":1482392573000,"empty":true}]'
    http_version: 
  recorded_at: Thu, 22 Dec 2016 07:42:34 GMT
recorded_with: VCR 3.0.3
