---
:metadata:
  :name: monitoring-heapster-controller
  :namespace: default
  :selfLink: "/api/v1/namespaces/default/replicationcontrollers/monitoring-heapster-controller"
  :uid: 1f2d2157-35f2-11e5-8917-001a4a5f4a00
  :resourceVersion: '122'
  :generation: 1
  :creationTimestamp: '2015-07-29T13:02:52Z'
  :labels:
    :name: heapster
:spec:
  :replicas: 1
  :selector:
    :name: heapster
  :template:
    :metadata:
      :creationTimestamp:
      :labels:
        :name: heapster
    :spec:
      :containers:
      - :name: heapster
        :image: kubernetes/heapster:v0.16.0
        :command:
        - "/heapster"
        - "--source=kubernetes:https://kubernetes"
        - "--sink=influxdb:http://monitoring-influxdb:80"
        :resources: {}
        :terminationMessagePath: "/dev/termination-log"
        :imagePullPolicy: IfNotPresent
      :restartPolicy: Always
      :dnsPolicy: ClusterFirst
:status:
  :replicas: 1
  :observedGeneration: 1
:kind: ReplicationController
:apiVersion: v1
